# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "CHANGE_ME"
name = "myapp"
handle = "myapp"
application_url = "https://myapp.pages.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "CHANGE_ME"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://myapp.pages.dev/auth/callback",
  "https://myapp.pages.dev/auth/shopify/callback",
  "https://myapp.pages.dev/api/auth/callback",
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
